name: Build with Mush

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Mush
      run: |
        curl -s https://raw.githubusercontent.com/javanile/mush/main/install.sh | bash
        echo "$HOME/.mush/bin" >> $GITHUB_PATH

    - name: Clone Mush repo
      run: git clone https://github.com/javanile/mush.git

    - name: Run Mush script
      run: |
        mush --version
        # replace with your actual mush script path and arguments
        mush ./src/main.sh

