name: Build with Mush

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Mush
      run: |
        mush

    

    - name: Run Mush script
      run: |
        mush --version
        # replace with your actual mush script path and arguments
        mush /src/main.sh

